DROP TABLE zipcodes;

CREATE TABLE zipcodes(RecordNumber int, Country string, City string, Zipcode int)
PARTITIONED BY (state string)
CLUSTERED BY (Zipcode) INTO 32 BUCKETS
ROW FORMAT DELIMITED FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INPATH '/root/zipcodes.csv' INTO TABLE zipcodes;

INSERT OVERWRITE LOCAL Directory '/root/HiveResult4'
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
SELECT * FROM zipcodes WHERE state='PR' and zipcode=704;
