services:
    postgres:
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=Password1#
    # Redis DB
    redis:
        image: 'redis:latest'
        command: ["redis-server", "--protected-mode", "no"]
    api:
        build:
            context: ./server
        image: 'docker.io/sudheerkumar10081999/complex-api'
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=Password1#
            - PGPORT=5432
    worker:
      build: ./worker
      image: "docker.io/sudheerkumar10081999/complex-worker"
      environment:
         - REDIS_HOST=redis
         - REDIS_PORT=6379
    client:
      build: ./client
      image: "docker.io/sudheerkumar10081999/complex-client"

   # nginx 
    nginx:
      depends_on:
            - api
            - client
      restart: always
      build: ./nginx
      ports:
            - '8082:80'